//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury.Language.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mercury.Language.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare property &apos;{0}.{1}&apos;..
        /// </summary>
        internal static string CANNOT_COMPARE_PROPERTY {
            get {
                return ResourceManager.GetString("CANNOT_COMPARE_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare values. {0}.
        /// </summary>
        internal static string CANNOT_COMPARE_VALUES {
            get {
                return ResourceManager.GetString("CANNOT_COMPARE_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection counts for property &apos;{0}.{1}&apos; do not match..
        /// </summary>
        internal static string COLLECTION_COUNTS_FOR_PROPERTY_DO_NOT_MATCH {
            get {
                return ResourceManager.GetString("COLLECTION_COUNTS_FOR_PROPERTY_DO_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source or/and Destination Objects are null.
        /// </summary>
        internal static string CORE_SOURCE_DESTINATION_OBJECTS_ARE_NULL {
            get {
                return ResourceManager.GetString("CORE_SOURCE_DESTINATION_OBJECTS_ARE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} in property collection &apos;{1}.{2}&apos; does not match..
        /// </summary>
        internal static string ITEM_IN_PROPERTY_COLLECTION_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("ITEM_IN_PROPERTY_COLLECTION_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch with property &apos;{0}.{1}&apos; found..
        /// </summary>
        internal static string MISMATCH_WITH_PROPERTY_FOUND {
            get {
                return ResourceManager.GetString("MISMATCH_WITH_PROPERTY_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Property or Method {0} is not implemented..
        /// </summary>
        internal static string PROPERTY_OR_METHOD_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("PROPERTY_OR_METHOD_NOT_IMPLEMENTED", resourceCulture);
            }
        }
    }
}
